version: '3.8'
services:
  db:
    image: postgres:17
    container_name: tablica_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Ksandr_Test_DB_01
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
    ports:
      - "5432:5432"
    networks:
      - tablica_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tablica_backend
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - tablica_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tablica_frontend
    ports:
      - "3000:80"
    networks:
      - tablica_network

volumes:
  db_data:

networks:
  tablica_network:
    driver: bridge